RAITO-2126 | Add support for fetching tags (called labels) of data objects
raito-io/cli-plugin-gcp pull request #56
Opened 2023-12-07 07:54 UTC by TimmersThomas

First try for implementation:

- For Bigquery dataSets, tables and views not a big issue as it's inside the metaData of the called item
- For GCP projects it's also possible to retrieve it from it's metaData.
- For GCP organisation & folders tried to implement tag retrieval via https://github.com/googleapis/google-cloud-go/blob/resourcemanager/v1.9.4/resourcemanager/apiv3/tag_bindings_client.go#L206

Some open questions:
- As far as I can see we need extra permissions `resourcemanager.hierarchyNodes.listEffectiveTags` (and others?)
- Where exactly do we want to support tags right now?
- Are tags optional or mandatory? So what should happen if a tag request for GCP organisation or folders fails because the permission set isn't updated yet?

2023-12-07 08:15 UTC, rmennes commented
@codatoz To make a decision here, but I would make tags optional (and only include them as a flag is set). This will avoid breaking the CLI as well if additional permissions are required.

2023-12-07 08:30 UTC, codatoz commented
Fully agree to make tags optional (disabled by default to keep backwards compatibility).

We need to figure out the detailed permission requirements and document them well.
I would then support tags on all levels where possible.

2023-12-15 08:49 UTC, codatoz requested changes
Lets take 'GCP' for source. In snowflake we use 'Snowflake'

2023-12-15 09:27 UTC, codatoz approved these changes

2023-12-15 09:29 UTC, merged